[application]

[web.app]
# HTML title tag content
title = "Protein Comparison Tool"
out_dir = "dist"
base_path = "/protein-comparison-tool"


[web.watcher]
index_on_404 = true

[bundle]
targets = "web"