[application]
name = "protein-comparison"
out_dir = "dist"
asset_dir = "public"

[web.app]
# HTML title tag content
title = "protein-comparison"
base_path = "protein-comparison"


[web.watcher]
index_on_404 = true
reload_html = true

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = [
   # Include from public_dir.
   "./assets/main.css",
   "https://dan-codes-badly.com/assets/theme.css"
]

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
